### ISSUE TITLE
Solving environment: failed with initial frozen solve. Retrying with flexible solve. Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

### ISSUE THREAD

**Issue by sanweishuwu100** [AutodeskAILab/BRepNet#15]
hi @zeroright

Could you try
```
conda install -c lambouj -c conda-forge occwl
```
and let me know if it works.  The source code will be published soon

_Originally posted by @JoeLambourne in https://github.com/AutodeskAILab/BRepNet/issues/1#issuecomment-918109206_

**Comment by sanweishuwu100** [comment]
When I use the method on the right, the following problems will appear.（conda install -c lambouj -c conda-forge occwl）
Solving environment: failed with initial frozen solve. Retrying with flexible solve，Can anyone help me? Thank you.

**Comment by JoeLambourne** [comment]
Hi @sanweishuwu100,

I'm also getting conda hanging when trying to create this environment.   The working hypothesis is than this is caused by [occwl issue 21](https://github.com/AutodeskAILab/occwl/issues/21).  We had problems with the jupyter viewer if we didn't lock down the version of ipykernel, but now it looks like the environment doesn't install at all, so a dependency must have changed somewhere.  I'm just checking with @pradeep-pyro about updating the package

**Comment by samParry** [comment]
Any update on the issue? I've run into a similar issue and can't properly install the repo.

**Comment by JoeLambourne** [comment]
Hi @samParry ,

Sorry you have been having trouble.   We have made a number of tweaks to the occwl library, but we still have issues with dependencies.   The solution which appears to be reliable is using `mamba` rather than conda to install packages.   Could you try 

```
conda install -n base mamba -c conda-forge
...
mamba install occwl -c lambouj -c conda-forge
```

and see if you can get the occwl library to install?

**Comment by JoeLambourne** [comment]
> When I use the above methodt, the following problems will appear. (base) PS C:\Users\19890> conda install -c lambouj -c conda-forge occwl Collecting package metadata (current_repodata.json): done Solving environment: failed with initial frozen solve. Retrying with flexible solve. Can anyone help me? Thank you.

I found that cleaning out my conda base environment helped avoid very long hangs.   I had accidentally installed lots of packages in there.  I followed some of the instructions [here](https://stackoverflow.com/questions/52830307/conda-remove-all-installed-packages-from-base-root-environment)
